#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
# IFS=$'\n\t'

curr_date="$(date '+%-d')"
day=${1:-$curr_date}
program=$(echo "day"$day*)

input=${2:-}

if [[ "$program" == *.rs ]]; then
    export RUST_BACKTRACE=1
    ex="cargo run"
elif [[ "$program" == *.rs ]]; then
    ex="python"
else
    echo "Unsupported program $program"
    exit 1
fi

if [[ $input == "-" ]]; then
    # pipe input from stdin
    $ex
elif [[ $input == "" ]]; then
    for file in input/day${day}_test* input/day${day}.txt; do
        if [[ -f $file ]]; then
            echo Running $file
            cat $file | $ex
        fi
    done
else
    cat $input | $ex
fi
